#ifndef TESTS_H
#define TESTS_H

/* Runtime OLED menu item IDs. K3 moves down and K4 starts an item. */
#define MODULE_TEST_OLED 1U
#define MODULE_TEST_BOARD_LED 2U
#define MODULE_TEST_BUZZER 3U
#define MODULE_TEST_MOTOR 4U
#define MODULE_TEST_ENCODER 5U
#define MODULE_TEST_BUTTONS 6U
#define MODULE_TEST_GRAY_SENSOR 7U
#define MODULE_TEST_GYRO 8U
#define MODULE_TEST_CAMERA_UART 9U
#define MODULE_TEST_OLED_I2C 10U
#define MODULE_TEST_GRAY_PID_TRACKING 11U
#define MODULE_TEST_GYRO_PID_CONTROL 12U
#define MODULE_TEST_MOTOR_SPEED_PID 13U
#define MODULE_TEST_DEBUG_UART 14U
#define MODULE_TEST_GIMBAL_UART 15U
#define MODULE_TEST_H24_FIGURE_EIGHT 16U

void module_test_run(void);

#endif
